### ISSUE TITLE
how can we add our own customizations to tailwind.config.js ?

### ISSUE THREAD

**Issue by vesper8** [optimistdigital/nova-tailwind#4]
First of all thanks a lot for releasing this! I've been wanting an easy way of adding the full Tailwind to Nova and this does the trick

I would like to know how we should go about if we need to add our own customizations to `tailwind.config.js` ? Such as adding custom colors or well any other customizations

It would be useful perhaps if it was possible to publish the `tailwind.config.js` and then have your package look for the existence of that file which would then load it instead of loading the package's version

I'm also curious about some of the customizations in your own `tailwind.config.js` and why it was necessary to redefine the widths for example? Could you comment on why those customizations were necessary?

Many thanks!

**Comment by Tarpsvo** [comment]
Hi.

You're better off just creating your own fork if you want customisation, there's no feasible way to make it possible via a Nova package (all the assets are built for production when releasing a version of this package, you can't modify then during runtime).

The config provided here is meant to just fill in the gaps and tries to avoid duplicate classes as much as possible. That's why the widths are overwritten in this config - to not include the widths that are already provided by Nova.

Good luck!
